apiVersion: v1
kind: Pod
metadata:
  name: jenkins-to-sql
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: jenkins-to-sql
      image: gbhat618/jenkins-to-sql:amd64
      imagePullPolicy: Always
      env:
        - name: DB_URL
          value: "jdbc:postgresql://hostname:port/dbname?user=myuser&password=myuserpass"
        - name: JENKINS_HOME
          value: /var/jenkins_home
        - name: POLL_INTERVAL_SECONDS
          value: "10"
      volumeMounts:
        - name: jenkins-home-volume
          mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-home-volume
      persistentVolumeClaim:
        claimName: jenkins-home-mm-0
  restartPolicy: Always